### ISSUE TITLE
Error found in first run, check Console

### ISSUE THREAD

**Issue by s3anyboy** [nathan-gs/ha-map-card#69] opened 2024-06-21 03:51 UTC
I see the message "Error found in first run, check Console" where the attributions listed, but I have looked in the logs and dont see anything related to this, even with debug: true in the card

**Comment by nathan-gs** [comment] 2024-06-23 09:40
And what does the browser console say?

**Comment by nathan-gs** [comment] 2024-06-25 18:03
@ildar170975 that's more or less the intended behavior.

**Comment by ildar170975** [comment] 2024-06-25 18:15
@nathan-gs 
I fully agree; may be the OP missed some required attribute?

**Comment by nathan-gs** [comment] 2024-06-25 18:27
Closing the issue @s3anyboy, but please reopen if you have more info.

**Closed by nathan-gs** 2024-06-25 18:27 UTC

**Comment by ildar170975** [comment] 2024-06-25 18:54
Another case - defining a non-existing entity:
![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/70e34386-655c-42ec-b12f-10e439b01c6d)

or an entity w/o coords:
![image](https://github.com/nathan-gs/ha-map-card/assets/71872483/b2a3563c-d4ee-43fb-9a7a-55a3016f8155)

I wonder - if a person is at home - then the entity does not have coords - then will we see an error?

**Comment by s3anyboy** [comment] 2024-06-25 19:11
> Another case - defining a non-existing entity: ![image](https://private-user-images.githubusercontent.com/71872483/342883069-70e34386-655c-42ec-b12f-10e439b01c6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDI3ODMsIm5iZiI6MTcxOTM0MjQ4MywicGF0aCI6Ii83MTg3MjQ4My8zNDI4ODMwNjktNzBlMzQzODYtNjU1Yy00MmVjLWIxMmYtMTBlNDM5YjAxYzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE5MDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiM2UwYjk3YjJhNTUzNWVhMTY2NzY4OGJiMGE0ZjlmYzExOTMzMmQxYTAzNGIwNzAzZTVkODdiMGY1ZGI5ZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kgim5vifOUppjrAiSgRF9YIuGBEY0aXL-PbV1hUB05Q)
> 
> or an entity w/o coords: ![image](https://private-user-images.githubusercontent.com/71872483/342883730-b2a3563c-d4ee-43fb-9a7a-55a3016f8155.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzNDI3ODMsIm5iZiI6MTcxOTM0MjQ4MywicGF0aCI6Ii83MTg3MjQ4My8zNDI4ODM3MzAtYjJhMzU2M2MtZDRlZS00M2ZiLTlhN2EtNTVhMzAxNmY4MTU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDE5MDgwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5MDZjNjJiOGY2OTY3OWM0MGYwOGMwYTdmZWUxMTY1NTFlNmU4Y2UyNTRjN2M2ZDJkYzMxZjY5YzU4OGUzMDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HqSNPW2cg6pkCO2Wx0PglVQRVmNheDR8y8VoisLehc0)
> 
> I wonder - if a person is at home - then the entity does not have coords - then will we see an error?

Yes, I have custom device_trackers to merge multiple location sensor sources and sometimes they do not provide GPS coords, so it seems this was the cause of the issue.

in 1.3.0 the map at least still loaded despite displaying this error, but after update to 1.4.0 the map is just a black/white screen if the problem entity is defined.
Not sure what can be done about this exactly, I will probably just have to stay on 1.3.0 for a while lol, thanks though.

**Comment by s3anyboy** [comment] 2024-08-12 17:16
|I updated to 1.4.0 and have fallback_x and y on every entity, yet the ones that do not have constant gps coordinates still seem to cause this error. I'm not sure what changed between 1.3 and 1.4 that made it so the entire map display breaks with this error instead of just not displaying the specific entity.
