### ISSUE TITLE
Not working for french geoservices?

### ISSUE THREAD

**Issue by vingerha** [nathan-gs/ha-map-card#18] opened 2024-05-04 05:28 UTC
Hi, I played around with the examples and really enjoyed that. 
After a bit of digging into local options, I found this site 
https://geoservices.ign.fr/services-geoplateforme-diffusion
There are 2 wms services, raster and vector and along the xml they both cover layer [EPSG:27572](https://epsg.io/27572) 
But neither of them show in the card...any idea why?
```
type: custom:map-card
zoom: 8
card_size: 6
wms:
  - url: >-
      https://data.geopf.fr/wms-v/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
    options:
      layers:
        - EPSG:27572
      format: image/png
tile_layer_url: https://basemaps.cartocdn.com/rastertiles/voyager/{z}/{x}/{y}.png
entities:
  - entity: zone.home
    display: icon
    size: 50

**Comment by nathan-gs** [comment] 2024-05-04 09:10
I changed your code to the following

```yaml
type: custom:map-card
zoom: 8
card_size: 6
wms:
  - url: https://data.geopf.fr/wms-v/ows?SERVICE=WMS
    options:
      layers:
        - EPSG:27572
      format: image/png
      attribution: GEOPF
      version: 1.3.0
x: 48.856697
'y': 2.351462

``` 

and if I then take a look at a request (`https://data.geopf.fr/wms-v/ows?SERVICE=WMS&service=WMS&request=GetMap&layers=EPSG%3A27572&styles=&format=image%2Fpng&transparent=false&version=1.3.0&width=256&height=256&crs=EPSG%3A3857&bbox=-156543.03392804097,6105178.3231936,0,6261721.357121641`):
```xml
<ServiceExceptionReport version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc https://data.geopf.fr/wms-v/schemas/wms/1.3.0/exceptions_1_3_0.xsd">
<ServiceException code="LayerNotDefined" locator="layers"> Could not find layer EPSG:27572 </ServiceException>
</ServiceExceptionReport>
```

So the layer is not correct.

**Comment by vingerha** [comment] 2024-05-04 11:55
What do you mean with not correct'...is this not correct for the card or is this incorrect for a WMS? If the latter, why would such a large organization deviate from a (is there) standard?

**Comment by nathan-gs** [comment] 2024-05-04 12:06
The layer __you__ specify is not the correct one, according to the error msg.

The card and server are following the WMS spec, but you have to use the right options of course. I did not immediately see which layer you should use though.

**Comment by nathan-gs** [comment] 2024-05-06 18:35
The list of WMS layers is published on the page itself:
https://geoservices.ign.fr/services-geoplateforme-diffusion#:~:text=Donn%C3%A9es%20du%20Service%20d'images%20WMS-Vecteur

(title Données du Service d'images WMS-Vecteur)

```yaml
type: custom:map-card
zoom: 8
card_size: 6
wms:
  - url: https://data.geopf.fr/wms-v/ows
    options:
      layers: CLEFVERTE
      format: image/png
      attribution: GEOPF
      version: 1.3.0
      transparant: true
x: 48.856697
'y': 2.351462

```
gives this result
![CLEFVERTE](https://github.com/nathan-gs/ha-map-card/assets/330943/0afe6c8e-c2d8-4ec4-b574-2424dda41628)

**Comment by vingerha** [comment] 2024-05-07 04:21
OK thanks, so the xml-inside section with layer ids is 'misleading' ?
And maybe a continued stupid question....how would I have had to find out to not use this, which the website states
```
https://data.geopf.fr/wms-v/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
```
but use this what you mention above:
```
https://data.geopf.fr/wms-v/ows
```

**Comment by nathan-gs** [comment] 2024-05-07 18:19
A good intro can be found here (and the QGIS part):
https://leafletjs.com/examples/wms/wms.html

The docs of the GeoPF website are a bit short and out of date, might be best to contact them.

**Comment by vingerha** [comment] 2024-05-08 09:13
Thanks... is on my to-learn-list now. Another thing I am interested in is the validity of the overlays. In the link above there are plenty of them that from the naming-only refer to 'current' data but I cannot find out what that means. As an example your Belgian air quality overlay, how would you know 'when' this was measured....could be years old as well ?

**Comment by vingerha** [comment] 2024-05-08 16:47
Adding ideas... I would like to extract all layers into a select list for HA so that I can dynamically change the overlay. Would you know if there is a standardized (you may laugh out loud) way to publish layers?

**Comment by nathan-gs** [comment] 2024-05-18 09:17
To be honest this will be very hard to implement since leaflet doesn't have that capability either. Not sure if there are any other javascript WMS libraries. 

Closing for now, as it works as intended.

**Closed by nathan-gs** 2024-05-18 09:17 UTC
Labels: invalid
