### ISSUE TITLE
Card is empty after a browser's page reload (F5) in a "yaml-mode" dashboard

### ISSUE THREAD

**Issue by ildar170975** [nathan-gs/ha-map-card#13] opened 2024-03-24 19:37 UTC
I started observing a very strange glitch:

1. Add a card to a yaml-mode view:
```
title: test-2
path: test-2
cards:

  - type: custom:map-card
    x: 10
    y: 10
```
2. Refresh a view page:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/8e2c6c39-6d20-40e6-a532-ed3909ebb719)

3. Card is shown, very good.
4. Reload a browser's page (F5 in Chrome).
5. Card is shown as empty:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/f02780eb-afef-4c45-bad0-a628f422379a)

There is a message in a console:
map-card.js?hacstag=734825457050:169 Uncaught TypeError: Cannot read properties of undefined (reading 'getContainer')
    at ResizeObserver.<anonymous>

In a "storage-mode" dashboard - I see no glitches, the card is shown after F5:

![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/bec760d6-bcf1-4bf9-b3d4-8d3ef4ba172f)

HA 2024.3.1
card 0.5.0
Chrome 123.0.6312.59 + Win10
same in FF

**Comment by nathan-gs** [comment] 2024-03-24 19:40
@Manuel-Materazzo I believe we introduced a small bug with the resizeobserver.

**Comment by Manuel-Materazzo** [comment] 2024-03-24 20:47
After a first investigation, i can see that:
- During a page refresh he `ResizeObserver` seems to get one final call when the card is already disposed, causing the `Uncaught TypeError` on YAML mode, and a `this.resize is not a function` error on standard mode.
- For some unknown reason, on YAML mode the `disconnectedCallback()` method gets called right before the first render, effectively disposing both the map and resize observer, i need to futher investigate on this behaviour.

**Comment by ildar170975** [comment] 2024-03-24 20:55
Also, in a "storage" mode I sometimes see "card not found" error after F5.
Sometimes need to press F5 again.
Sometimes this error comes only for a couple of seconds, then the card is properly shown.

Was not sure if this behaviour related to the discussed "empty card" issue - that is why have not registered an issue yet.

**Comment by Manuel-Materazzo** [comment] 2024-03-24 21:11
> Also, in a "storage" mode I sometimes see "card not found" error after F5. Sometimes need to press F5 again. Sometimes this error comes only for a couple of seconds, then the card is properly shown.

i can't seem to reproduce the issue, what version of HA are you on?

**Comment by ildar170975** [comment] 2024-03-24 21:28
HA 2024.3.1
card 0.5.0
Chrome 123.0.6312.59 + Win10

**Comment by nathan-gs** [comment] 2024-03-25 17:23
@ildar170975 can you test the latest version (v0.5.2), thanks to @Manuel-Materazzo it should be fixed. 

It's fixed in my HA.

**Comment by ildar170975** [comment] 2024-03-25 18:15
@nathan-gs 
Thanks a lot!

Now in both yaml & storage dashboards - the card is shown after F5.
No "grey card" as it was.

But sometimes (rather often - let's say 30% cases) -after F5 a "card not found error" occurs.
It is shown for less than 1 sec, then a card is shown properly.
Happens in both yaml & storage modes:

storage:
![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/7ddd57e9-e22a-47b4-b86c-eab56c879f48)

yaml:
![изображение](https://github.com/nathan-gs/ha-map-card/assets/71872483/e9a07076-d052-4a0a-bf0d-95b6ff8bc5ac)

**Comment by ildar170975** [comment] 2024-03-25 18:18
Shall we close the current issue & proceed with THIS problem in a separate issue?

**Comment by Manuel-Materazzo** [comment] 2024-03-25 18:42
I've tried to reproduce the issue on a fresh install of your setup, but to no avail. 
It's an issue related to HA lazy loading, as discussed on [this thread](https://community.home-assistant.io/t/custom-element-doesnt-exist-but-loads-a-few-seconds-later/266349).
If i'm to take a wild guess, it happens because we are fetching external libraries from unpkg, might be worth looking into a way of importing from HA itself.

**Comment by ildar170975** [comment] 2024-03-25 18:47
If this is long way & uneasy task - I would suggest to close this issue & create a new one, and let it be there until you guys sort it out. The issue is not crucial imho.

**Closed** 2024-03-25 19:10 UTC
Labels: bug
